name = "starlight-plugin-icons"
compatibility_date = "2025-04-01"
main = "src/worker.js"
routes = [ { pattern = "docs.rettend.me", custom_domain = true } ]

[assets]
directory = "./dist"
binding = "ASSETS"
run_worker_first = true
